name: Checks

on:
  push:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-22.04
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - run: just fmt
