name: Checks

on:
  push:
  workflow_dispatch:

jobs:
  fmt:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      # Install just
      - uses: extractions/setup-just@v1
      # Install lua
      - uses: leafo/gh-actions-lua@v9
      # Install luarocks
      - uses: leafo/gh-actions-luarocks@v4
      # Run formatters
      - run: just fmt
